### PR TITLE
Added an important java file.

### PR DESCRIPTION
**Pull request by eriklandell**

### CODE REVIEW

**Comment by PeterBell** [comment]
I can't see that this would do any harm, I'm :+1:

**Comment by jimon** [comment]
I can write here yay

**Comment by Milleeagle** [comment]
This is the best thing ever!

**Comment by rikardjaksch** [comment]
:-1:

**Comment by daheri** [comment]
awesome!

**Comment by cjrams** [comment]
nice :+1:

**Comment by samny** [comment]
Awesome clean code :+1

**Comment by Drabuna** [comment]
Please provide documentation for this :-1:

**Comment by Milleeagle** [comment]
I changed my mind, this sucks!

**Comment by tbryntse** [comment]
Awesome stuff!

**Comment by JonathanMagnusson** [comment]
:+1

**Comment by tbryntse** [comment]
:8ball:

**Comment by PeterBell** [comment]
:poop:

**Comment by chrstphe** [comment]
:poop:

**Comment by asRIA** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by samny** [comment]
:point_up:

**Comment by PeterBell** [comment]
harry-potter-congrats

**Comment by tbryntse** [comment]
zlatan

**Comment by daheri** [comment]
:poodle:

**Comment by mnystr** [comment]
💩

**Pull request merged**
